- project:
    check:
      jobs:
        - thoth-coala
        - thoth-pytest
    gate:
      jobs:
        - thoth-coala
        - thoth-pytest
    kebechet-auto-gate:
      jobs:
        - thoth-coala
        - thoth-pytest
    post:
      jobs:
        - "trigger-build":
            vars:
              cluster: "paas.psi.redhat.com"
              namespace: "thoth-test-core"
              buildConfigName: "package-extract"
